PZAI/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('kanban.urls')),
    path('admin/', admin.site.urls),
]

kanban/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from psycopg2 import paramstyle
from . import views

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
]

task_crud_patterns = [
    path('task/<uuid:pk>', views.TaskDetailView.as_view(), name='task-detail'),
    path('task/add', views.TaskCreate.as_view(), name='task-add'),
    path('task/edit/<uuid:pk>', views.TaskUpdate.as_view(), name='task-edit'),
    path('task/delete/<uuid:pk>', views.TaskDelete.as_view(), name='task-delete'),
    path('task/archive/<uuid:pk>', views.TaskArchive.as_view(), name='task-archive'),
    path('task/restore/<uuid:pk>', views.TaskRestore.as_view(), name='task-restore'),
]
urlpatterns += task_crud_patterns

task_action_patterns = [
    path('task/actions/increase_priority/<uuid:pk>', views.TaskAction.as_view(), {'action': 'increase_priority'},
         name='task-action-increase_priority'),
    path('task/actions/decrease_priority/<uuid:pk>', views.TaskAction.as_view(), {'action': 'decrease_priority'},
         name='task-action-decrease_priority'),
    path('task/actions/increase_status/<uuid:pk>', views.TaskAction.as_view(), {'action': 'increase_status'},
         name='task-action-increase_status'),
    path('task/actions/decrease_status/<uuid:pk>', views.TaskAction.as_view(), {'action': 'decrease_status'},
         name='task-action-decrease_status'),
    path('task/actions/max_priority/<uuid:pk>', views.TaskAction.as_view(), {'action': 'max_priority'},
         name='task-action-max_priority'),
    path('task/actions/min_priority/<uuid:pk>', views.TaskAction.as_view(), {'action': 'min_priority'},
         name='task-action-min_priority'),
]
urlpatterns += task_action_patterns

task_comment_crud_patterns = [
    path('task_comment/add/', views.TaskCommentCreate.as_view(), name='taskcomment-add'),
    path('task_comment/add/<uuid:task_pk>', views.TaskCommentCreate.as_view(), name='taskcomment-add-specific'),
    path('task_comment/edit/<uuid:pk>', views.TaskCommentUpdate.as_view(), name='taskcomment-edit-specific'),
    path('task_comment/delete/<uuid:pk>', views.TaskCommentDelete.as_view(), name='taskcomment-delete'),
]
urlpatterns += task_comment_crud_patterns

account_views = [
    path('accounts/tasks/', views.UserTasks.as_view(), name='user-tasks'),
    path('accounts/tasks/<group>', views.UserTasksGroups.as_view(), name='user-tasks-groups'),
    path('/<group>', views.AllTasksGroup.as_view(), name='all-tasks-groups'),
    
    path('/users/',views.KanbanUsers.as_view(),name ='user-users' ),
    path('/users/<name>/<group>/<param>',views.mod_group,name ='user-gr' ),

    path('accounts/login/', views.KanbanLogin.as_view(), name='accounts-login'),
    path('accounts/logout/', views.KanbanLogout.as_view(), name='accounts-logout'),
#     path('accounts/sign_up/', views.KanbanSignUp.as_view(), name='accounts-sign_up'),
    path('accounts/sign_up/', views.KanbanSignUp.as_view(), name='accounts-sign_up'),
    path('accounts/activate/<id>',  views.activate, name='activate'),
]
urlpatterns += account_views

kanban/models/task.py
import datetime
from tokenize import group
import uuid
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import Group

class Task(models.Model):
    class Meta:
        ordering = ['-date_modified']

    STATUS_CHOICES = {
        ('TODO', 'To Do'),
        ('PROG', 'In Progress'),
        ('TEST', 'In Testing'),
        ('DONE', 'Done'),
    }

    uuid = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)

    priority = models.IntegerField(default=0)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=4, choices=STATUS_CHOICES, default='TODO')

    date_created = models.DateTimeField(default=datetime.datetime.now())
    date_modified = models.DateTimeField(default=datetime.datetime.now())

    
    
    User = get_user_model()
    users = User.objects.all()
    print(users)

    usrs = {
        ('TODO', 'To Do'),
        ('PROG', 'In Progress'),
        ('TEST', 'In Testing'),
        ('DONE', 'Done'),
    }
    users_toulpe = {('No Author','No Author')}


    for user in users:
        print (user.username)
        users_toulpe.add((user.username,user.username))
    print(users_toulpe)

    groups_toulpe = {('default','default')}
    groups = Group.objects.all()

    for group in groups:
        print(group.name)
        groups_toulpe.add((group.name,group.name))
    print(groups_toulpe)

    author = models.CharField(max_length=200, choices =users_toulpe, default='No_Author')
    group = models.CharField(max_length=200, choices =groups_toulpe, default='default')
    archive = models.BooleanField(default=False)

    
    def __str__(self):
        return '{title}'.format(title=self.title)

    def get_absolute_url(self):
        return reverse('task-detail', kwargs={'pk': self.uuid})

    def increase_status(self) -> None:
        if self.status == 'TODO':
            self.status = 'PROG'
        elif self.status == 'PROG':
            self.status = 'TEST'
        elif self.status == 'TEST':
            self.status = 'DONE'

        self.save()

    def decrease_status(self) -> None:
        if self.status == 'PROG':
            self.status = 'TODO'
        elif self.status == 'TEST':
            self.status = 'PROG'
        elif self.status == 'DONE':
            self.status = 'TEST'

        self.save()

    def max_priority(self) -> None:
        cur_max_priority = Task.objects.all().aggregate(models.Max('priority'))['priority__max']

        self.priority = cur_max_priority + 1
        self.save()

    def min_priority(self) -> None:

        cur_min_priority = Task.objects.all().aggregate(models.Min('priority'))['priority__min']

        self.priority = cur_min_priority - 1
        self.save()

kanban/models/task_comment.py
from django.db import models
import datetime
import uuid

from .import Task


class TaskComment(models.Model):
    class Meta:
        ordering = ['-date_created']

    uuid = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4())

    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    text = models.TextField()

    date_created = models.DateTimeField(default=datetime.datetime.now())
    date_modified = models.DateTimeField(default=datetime.datetime.now())
    author = models.CharField(max_length=200, default='No Author')

    def __str__(self):
        return '{author} - {task}:{text}...'.format(author=self.author, task=self.task.title, text=self.text[:25])

kanban/views/allTasksGroup.py
from tokenize import group
from . import Index
from django.contrib.postgres.search import SearchVector
from ..models import Task


class AllTasksGroup(Index):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print("--------------------------------------")

        group = kwargs['group']
        if group == 'all':
            groups = []
            for group in self.request.user.groups.all():
                print(group.name)
                groups.append(group.name)
            print(groups)
            todo_tasks = Task.objects.filter(status='TODO', group__in=groups)
            prog_tasks = Task.objects.filter(status='PROG', group__in=groups)
            test_tasks = Task.objects.filter(status='TEST', group__in=groups)
            done_tasks = Task.objects.filter(status='DONE', group__in=groups)

        else :
            todo_tasks = Task.objects.filter(status='TODO', group=group)
            prog_tasks = Task.objects.filter(status='PROG', group=group)
            test_tasks = Task.objects.filter(status='TEST', group=group)
            done_tasks = Task.objects.filter(status='DONE', group=group)

        context['TODO_list'] = todo_tasks.order_by('-priority')[:15]
        context['PROG_list'] = prog_tasks.order_by('-priority')[:15]
        context['TEST_list'] = test_tasks.order_by('-priority')[:15]
        context['DONE_list'] = done_tasks.order_by('-priority')[:15]

        return context

kanban/views/index.py
from django.views.generic import  TemplateView

from ..models import Task

class Index(TemplateView):
    template_name = 'kanban/index.html'


    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)

        groups = []
        for group in self.request.user.groups.all():
            print(group.name)
            groups.append(group.name)
        print(groups)

        todo_tasks = Task.objects.filter(status='TODO', group__in=groups)
        prog_tasks = Task.objects.filter(status='PROG', group__in=groups)
        test_tasks = Task.objects.filter(status='TEST', group__in=groups)
        done_tasks = Task.objects.filter(status='DONE', group__in=groups)



        context['TODO_list'] = todo_tasks.order_by('-priority')[:15]
        context['PROG_list'] = prog_tasks.order_by('-priority')[:15]
        context['TEST_list'] = test_tasks.order_by('-priority')[:15]
        context['DONE_list'] = done_tasks.order_by('-priority')[:15]

        return context

kanban/views/kanbanLogin.py
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

class KanbanLogin(auth_views.LoginView):
    template_name = 'registration/login.html'
    extra_context = {'next': reverse_lazy('index')}

kanban/views/kanbanLogout.py
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

class KanbanLogout(auth_views.LogoutView):
    next_page = reverse_lazy('index')
    template_name = 'registration/logout.html'

kanban/views/kanbanSignUp.py
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

# from django.contrib.auth.forms import UserCreationForm
from kanban.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.core.mail import send_mail

from django.contrib.sites.shortcuts import get_current_site  
from django.utils.encoding import force_bytes  
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode  
from django.template.loader import render_to_string  
# from .tokens import account_activation_token  
from django.contrib.auth.models import User  
from django.core.mail import EmailMessage  
from django.http import HttpResponse  
from django.shortcuts import render, redirect  
from django.contrib.auth import login, authenticate  

class KanbanSignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("index")
    template_name = "registration/sign_up.html"

def signup(request):  
    if request.method == 'POST':  
        form = UserCreationForm(request.POST)  
        print("POOOOOOOOOOOOOOOOOOOSSSSSSSSSSSSSSSSSTTTTTTTTTTTT")
        # if form.is_valid():  
        # save form in the memory not in database  
        user = form.save(commit=False)  
        user.is_active = False  
        # user.save()  
        # to get the domain of the current site  
        current_site = get_current_site(request)  
        mail_subject = 'Activation link has been sent to your email id'  
        to_email = form.cleaned_data.get('email')
        mail_subject = "Link"
        message = "test"
        send_message = EmailMessage(mail_subject, message, to=[to_email])
        send_message.content_subtype = "html"
        send_message.send()
        # message = "Test msql"
        # # render_to_string('registration/login.html', {  
        # #     'user': user,  
        # #     'domain': current_site.domain,  
        # #     'uid':urlsafe_base64_encode(force_bytes(user.pk)),  
        # #     'token': '1234567890'#account_activation_token.make_token(user),  
        # # })  
        # to_email = form.cleaned_data.get('email')  
        # email = EmailMessage(  
        #             mail_subject, message, to=[to_email]  
        # )  
        # email.send()  
        print('end')
        val = send_mail(
            'Subject here',
            'Here is the message.',
            'from@example.com',
            ['matzur2020@gmail.com'],
            fail_silently=False,
        )
        print(val)
        return HttpResponse('Please confirm your email address to complete the registration')  
    else:  
        return KanbanSignUp.as_view()
 

kanban/views/kanbanUsers.py
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

# from django.contrib.auth.forms import UserCreationForm
from kanban.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.core.mail import send_mail

from django.contrib.sites.shortcuts import get_current_site  
from django.utils.encoding import force_bytes  
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode  
from django.template.loader import render_to_string  
# from .tokens import account_activation_token  
from django.contrib.auth.models import User  
from django.core.mail import EmailMessage  
from django.http import HttpResponse  
from django.shortcuts import render, redirect  
from django.contrib.auth import login, authenticate  
from django.contrib.auth.models import User,Group
from . import Index

class KanbanUsers(Index):
    template_name = "kanban/users.html"
    def get_context_data(self, **kwargs):
        
        context = super().get_context_data(**kwargs)
        # model = User
        fields = '__all__'
        users = User.objects.all()
        groups = Group.objects.all()

        success_url = reverse_lazy("index")
        context['users'] = User.objects.all()
        context['groups'] = Group.objects.all()
        return context

kanban/views/taskActions.py
from django.urls import reverse
from django.shortcuts import  get_object_or_404
from django.views.generic import RedirectView


from ..models import Task

class TaskAction(RedirectView):

    def get_redirect_url(self, *args, **kwargs):

        action = kwargs.get('action')
        task_pk = kwargs.get('pk')

        task = get_object_or_404(Task, pk=task_pk)

        if action == 'increase_priority':
            task.priority += 1

        elif action == 'decrease_priority':
            task.priority -= 1

        elif action == 'increase_status':
            task.increase_status()

        elif action == 'decrease_status':
            task.decrease_status()

        elif action == 'max_priority':
            task.max_priority()

        elif action == 'min_priority':
            task.min_priority()
        task.save()
        return reverse('index')

kanban/views/taskArchive.py
from django.urls import reverse
from django.shortcuts import  get_object_or_404
from django.views.generic import RedirectView
from django.views.generic.edit import UpdateView

from ..models import Task

class TaskArchive(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        # context = super().get_context_data(**kwargs)

        print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxXX")
        task_pk = kwargs.get('pk')
        print(task_pk)
        task = get_object_or_404(Task, pk=task_pk)
        task.archive = True
        task.save()
        print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxXX")
        return reverse('index')

class TaskRestore(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        # context = super().get_context_data(**kwargs)

        print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxXX")
        task_pk = kwargs.get('pk')
        print(task_pk)
        task = get_object_or_404(Task, pk=task_pk)
        task.archive = False
        task.save()
        print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxXX")
        return reverse('index')

kanban/views/taskCommentForms.py
import datetime

from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from kanban.models import TaskComment


class TaskCommentCreate(CreateView):
    model = TaskComment
    fields = '__all__'
    template_name = 'kanban/taskcomment_create_form.html'

    def get_initial(self):

        initial = {'task': self.kwargs.get('task_pk')}

        if self.request.user.is_authenticated:
            initial.update({'author': self.request.user.username})

        return initial

    def get_success_url(self):
        return reverse_lazy('task-detail', kwargs={'pk':self.object.task.uuid})


class TaskCommentUpdate(UpdateView):
    model = TaskComment
    fields = '__all__'
    template_name = 'kanban/taskcomment_edit_form.html'

    def get_success_url(self):
        return reverse_lazy('task-detail', kwargs={'pk':self.object.task.uuid})


class TaskCommentDelete(DeleteView):
    model = TaskComment

    def get_success_url(self):
        return reverse_lazy('task-detail', kwargs={'pk':self.object.task.uuid})

kanban/views/taskDetailView.py
from django.views.generic import DetailView

from ..models import Task


class TaskDetailView(DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'kanban/task_detail.html'

kanban/templates/kanban/index.html
{% extends 'kanban/kanban_base.html' %}


{% block title %}
    Kanban Board
{% endblock %}

{% block content %}

    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Django Kanban boards</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'index' %}">All Tasks
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user-tasks' %}">My Tasks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'task-add' %}">Add Task</a>
                        </li>
                        {% if user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user-users' %}">Users</a>
                        </li>
                        {% endif %}
                    {% endif %}
                </ul>
                <span class="navbar-text">
                    {% if user.is_authenticated %}
                        <strong>{{ user.email }}</strong>
                        <button type="button" class="btn btn-outline-light">
                            <a href="{% url 'accounts-logout' %}" style="text-decoration:none">Logout</a>
                        </button>
                    {% else %}
                        <button type="button" class="btn btn-outline-light">
                            <a href="{% url 'accounts-login' %}" style="text-decoration:none">Login</a>
                        </button>
                    {% endif %}
                </span>
            </div>
        </nav>

        <div class="row">
            <h2>Dashboard groups
                <span class="badge badge-info">
                    {% if "/accounts/tasks/" in request.path %}
                        My task
                    {% else %}
                        All tasks
                    {% endif %}
                </span>
            </h2>

            <div class="btn-group" role="group" aria-label="Basic example">
                <form method="get" class="form-group">
                    {% if "/accounts/tasks/" in request.path %}
                        <span class="badge badge-info">
                            <a href="{% url 'user-tasks' %}" style="color:#ffffff; text-decoration:none">My tasks</a>
                        </span>
                        {% for gr in user.groups.all %}
                            <span class="badge badge-info">
                                <a href="{% url 'user-tasks-groups' gr.name %}" style="color:#ffffff; text-decoration:none">{{ gr.name }}</a>
                            </span>
                        {% endfor %}
                    {% else %}
                        <span class="badge badge-info">
                            <a href="{% url 'all-tasks-groups' 'all' %}" style="color:#ffffff; text-decoration:none">All tasks</a>
                        </span>
                        {% for gr in user.groups.all %}
                            <span class="badge badge-info">
                                <a href="{% url 'all-tasks-groups' gr.name %}" style="color:#ffffff; text-decoration:none">{{ gr.name }}</a>
                            </span>
                        {% endfor %}
                    {% endif %}
                </form>

            </div>
        </div>

        <div class="container-fluid pt-3">
            <h3 class="font-weight-light text-white">Kanban Board</h3>
            <div class="small  text-light">Drag and drop between swim lanes</div>
            <div
                class="row flex-row flex-sm-nowrap py-3">
                <!-- <div class="row justify-content-center"> -->
                <div class="col-sm-6 col-md-4 col-xl-3">
                    {% include 'kanban/index_task_list.html' with task_list=TODO_list title='Tasks To Do' %}
                </div>
                <div class="col-sm-6 col-md-4 col-xl-3">
                    {% include 'kanban/index_task_list.html' with task_list=PROG_list title='Tasks In Progress' %}
                </div>
                <div class="col-sm-6 col-md-4 col-xl-3">
                    {% include 'kanban/index_task_list.html' with task_list=TEST_list title='Tasks In Testing' %}
                </div>
                <div class="col-sm-6 col-md-4 col-xl-3">
                    {% include 'kanban/index_task_list.html' with task_list=DONE_list title='Tasks Done' %}
                </div>
                <!-- </div> -->
            </div>
        </div>
    </div>


{% endblock %}

kanban/templates/kanban/index_task_list.html
<div class="card bg-light" ondrop="drop(event,'{{ title }}')" ondragover="allowDrop(event)">
    <div class="card-body">
        <h6 class="card-title text-uppercase text-truncate py-2">{{ title }}</h6>
        <div class="items border border-light">
            {% if task_list %}
                {% for task in task_list %}
                    {% if task.archive is False or user.is_superuser %}
                        <div class="card draggable shadow-sm" draggable="true" ondragend="dropTask(event,'{{ title }}','{{ task.uuid }}')">
                            {% include 'kanban/index_task_panel.html' with task=task %}
                        </div>
                        <div class="dropzone rounded">
                            &nbsp;
                        </div>
                    {% endif %}
                {% endfor %}
            {% else %}
                No Tasks Present
            {% endif %}
        </div>
    </div>
</div>
<script>
    var task_board_name_new;
    function allowDrop(event) {
        event.preventDefault();
    }
    function drop(event, task_board_name) {
        console.log('Task board name switch --> ', task_board_name)
        task_board_name_new = task_board_name
        event.preventDefault();
    }
    function dropTask(event, task_board_name_current, uuid) {
        const Http = new XMLHttpRequest();
        console.log(task_board_name_new, uuid,)
        console.log('Current task board : ', task_board_name_current)
        var start_board = 0
        var end_board = 0


        switch (task_board_name_current) {
            case 'Tasks To Do': start_board = 1;
                break;
            case 'Tasks In Progress': start_board = 2;
                break;
            case 'Tasks In Testing': start_board = 3;
                break;
            case 'Tasks Done': start_board = 4;
                break;
        }

        switch (task_board_name_new) {
            case 'Tasks To Do': end_board = 1;
                break;
            case 'Tasks In Progress': end_board = 2;
                break;
            case 'Tasks In Testing': end_board = 3;
                break;
            case 'Tasks Done': end_board = 4;
                break;
        }

        var diff = end_board - start_board

        if (diff > 0) {
            for (let i = 0; i < diff; i++) {
                console.log(i)
                document.location.href = '/task/actions/increase_status/' + uuid
            }
        }
        if (diff < 0) {
            for (let i = 0; i < Math.abs(diff); i++) {
                console.log(i)
                window.location.href = '/task/actions/decrease_status/' + uuid
            }
        }
        console.log(start_board, end_board, end_board - start_board);

        // document.location.href = 'task/edit/' + uuid

    }
</script>

kanban/templates/kanban/task_create_form.html
{% extends 'kanban/kanban_base.html' %}
{% load widget_tweaks %}
{% block title %}
    Add Task
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="card">
                <div class="card-body">
                    <h2>Add Task</h2>
                    <div class="login-wrap p-4 p-md-5">
                        <div class="row justify-content-center py-md-5">
                            <form method="post" novalidate>
                                {% csrf_token %}
                                {% for field in form.visible_fields %}
                                    {% if field.label == 'Priority' or field.label == 'Title' or field.label == 'Description' or field.label == 'Status' or field.label == 'Author' or field.label == 'Group' %}
                                        {{ field.label_tag }}
                                        {% render_field field class="form-control" %}
                                    {% else %}
                                        {{ field.as_hidden }}
                                    {% endif %}
                                {% endfor %}
                                <br/>
                                <button type="submit" class="btn btn-primary" value="Save">Submit</button>
                                <button type="button" class="btn btn-secondary">
                                    <a href="{% url 'index' %}" style="color:#ffffff; text-decoration:none">Back To Board</a>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

kanban/templates/kanban/task_detail.html
{% extends 'kanban/kanban_base.html' %}

{% block title %}Task:
    {{ task.title }}
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="card">
                <div class="card-body">
                    <h2>Task:
                        {{ task.title }}</h2>
                    <strong>Status:
                        {{ task.get_status_display }}
                        |</strong>
                    <button type="button" class="btn btn-primary">
                        <a href="{% url 'task-edit' task.uuid %}" style="color:#ffffff; text-decoration:none">Edit</a>
                    </button>
                    <button type="button" class="btn btn-secondary">
                        <a href="{% url 'index' %}" style="color:#ffffff; text-decoration:none">Back To Board</a>
                    </button>

                    <hr>


                        <p>
                            <strong>Description</strong>
                            <br>
                                {{ task.description }}
                            </p>

                            <p>
                                <strong>Comments</strong>
                                <br>
                                    <a href="{% url 'taskcomment-add-specific' task_pk=task.uuid %}">Add Comment</a>
                                    {% if task.taskcomment_set.all %}
                                        <ul>
                                            {% for task_comment in task.taskcomment_set.all %}
                                                <li>
                                                    <p>
                                                        {{ task_comment.text }}</p>
                                                    {{ task_comment.author }}
                                                    -
                                                    {{ task_comment.date_created }}
                                                    -
                                                    <a href="{% url 'taskcomment-edit-specific' pk=task_comment.pk %}">
                                                        Edit</a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}
                                </p>

                                <p>
                                    Author:
                                    {{ task.author }}
                                    <br>
                                        Group:
                                        {{ task.group }}
                                        <br>
                                            Date Created:
                                            {{ task.date_created }}
                                            <br>
                                                Last Modified:
                                                {{ task.date_modified }}
                                                <br></p>


                                            </div>
                                        </div>
                                    </div>
                                </div>


                            {% endblock %}
                        </p>
                    </p>

kanban/templates/kanban/taskcomment_create_form.html
{% extends 'kanban/kanban_base.html' %}

{% block title %}
    Add Comment
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="card">
                <div class="card-body">
                    <h2>Add Comment</h2>

                    <form method="post">
                        {% csrf_token %}
                        <table>
                            {{ form.as_table }}
                        </table>

                        <input type="submit" value="Save"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}